const project='b8hapo09',dataset='production';
export const filter='_type == "journal" && !(_id in path("drafts.**")) && !(_id in path("versions.**"))';
export async function query(q,params={}){const url=new URL(`https://${project}.api.sanity.io/v2025-02-19/data/query/${dataset}`);url.searchParams.set('query',q);url.searchParams.set('perspective','published');for(const [k,v]of Object.entries(params))url.searchParams.set('$'+k,JSON.stringify(v));const r=await fetch(url,{cache:'no-store',credentials:'omit'});if(!r.ok)throw new Error('Could not load journal');return (await r.json()).result;}
export function imageURL(image,width=1400){const ref=image?.asset?._ref;if(typeof ref!=='string')return null;const m=/^image-([a-zA-Z0-9]+)-(\d+x\d+)-(jpg|jpeg|png|webp|gif|avif)$/.exec(ref);return m?`https://cdn.sanity.io/images/${project}/${dataset}/${m[1]}-${m[2]}.${m[3]}?w=${width}&fit=max&auto=format`:null;}
export const labels={ko:{diary:'일기',club:'모임 기록',experiment:'독서 실험',reflection:'배운 점'},en:{diary:'Diary',club:'Club notes',experiment:'Experiments',reflection:'Reflections'}};
export function translated(post,lang){return lang==='en'?{title:post.titleEn||post.title,excerpt:post.excerptEn||post.excerpt,body:post.bodyEn?.length?post.bodyEn:post.body,original:!post.bodyEn?.length}:{title:post.title,excerpt:post.excerpt,body:post.body,original:false};}
export function dateText(date,lang){const d=new Date(date);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat(lang==='en'?'en-US':'ko-KR',{year:'numeric',month:'long',day:'numeric',timeZone:'America/Los_Angeles'}).format(d);}
export function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
export function card(post,lang){const t=translated(post,lang);const a=el('a',undefined,'entry-card');a.href='/journal/'+encodeURIComponent(post._id)+(lang==='en'?'?lang=en':'');const url=imageURL(post.cover,750);if(url){const img=el('img');img.src=url;img.alt=post.cover.alt||'';img.loading='lazy';a.append(img)}else{const motif=el('div',undefined,'entry-cover');motif.append(el('span',labels[lang][post.category]||labels[lang].diary),el('i','L.'));a.append(motif)}const content=el('div',undefined,'entry-copy');content.append(el('div',dateText(post.publishedAt||post._createdAt,lang),'entry-date'),el('h2',t.title||'Untitled'));if(t.excerpt)content.append(el('p',t.excerpt));content.append(el('span',lang==='en'?'Read this entry ↗':'기록 읽기 ↗','entry-link'));a.append(content);return a;}
export async function loadHome(lang){const root=document.querySelector('#latest-journal');if(!root)return;try{const posts=await query(`*[${filter}] | order(publishedAt desc, _id asc)[0...3]{_id,_createdAt,title,titleEn,excerpt,excerptEn,publishedAt,category,cover}`);root.replaceChildren();if(posts.length)posts.forEach(p=>root.append(card(p,lang)));else root.append(el('div',lang==='en'?'The notebook is open. Lumi’s first entry will appear here after it is published.':'노트의 첫 장을 펼쳤어요. 루미가 첫 글을 발행하면 이곳에 소개됩니다.','journal-empty'));}catch{root.replaceChildren(el('p',lang==='en'?'We couldn’t load the journal. Please try again shortly.':'기록을 불러오지 못했어요. 잠시 후 다시 확인해주세요.','journal-empty'));}}
