import {defineConfig,defineField,defineType} from 'sanity';
import {structureTool} from 'sanity/structure';
const richText = [{type:'block',styles:[{title:'본문 / Normal',value:'normal'},{title:'소제목 / Heading',value:'h2'},{title:'작은 제목 / Subheading',value:'h3'},{title:'인용 / Quote',value:'blockquote'}],marks:{decorators:[{title:'굵게 / Bold',value:'strong'},{title:'기울임 / Italic',value:'em'}],annotations:[{name:'link',type:'object',title:'링크 / Link',fields:[{name:'href',type:'url',title:'URL',validation:R=>R.uri({scheme:['http','https','mailto']})}]}]}}, {type:'image',options:{hotspot:true},fields:[{name:'alt',title:'사진 설명 / Alt text',type:'string',validation:R=>R.required()},{name:'caption',title:'사진 아래 설명 / Caption',type:'string'}]}];
const post=defineType({name:'journal',title:'루미의 저널 / Lumi’s Journal',type:'document',groups:[{name:'story',title:'글쓰기 / Write',default:true},{name:'english',title:'영어 번역 / English'},{name:'settings',title:'발행 정보 / Details'}],initialValue:()=>({author:'Lumi',category:'diary',publishedAt:new Date().toISOString()}),fields:[
 defineField({name:'title',title:'제목 / Title',type:'string',group:'story',validation:R=>R.required().max(120)}),
 defineField({name:'excerpt',title:'목록에 보일 한 문장 / Short introduction',type:'text',rows:3,group:'story',validation:R=>R.max(300)}),
 defineField({name:'cover',title:'대표 사진 / Cover image',type:'image',options:{hotspot:true},group:'story',fields:[{name:'alt',type:'string',title:'사진 설명 / Alt text',validation:R=>R.required()},{name:'caption',type:'string',title:'사진 아래 설명 / Caption'}]}),
 defineField({name:'body',title:'오늘의 기록 / Your story',description:'어떤 일이 있었나요? 무엇을 느꼈고, 다음엔 무엇을 해보고 싶나요? / What happened? How did you feel? What will you try next?',type:'array',of:richText,group:'story',validation:R=>R.required().min(1)}),
 defineField({name:'titleEn',title:'영어 제목 / English title',type:'string',group:'english'}),
 defineField({name:'excerptEn',title:'영어 소개 / English introduction',type:'text',rows:3,group:'english'}),
 defineField({name:'bodyEn',title:'영어 본문 / English story',type:'array',of:richText,group:'english'}),
 defineField({name:'publishedAt',title:'기록 날짜 / Entry date',type:'datetime',group:'settings',description:'글 목록은 이 날짜의 최신순으로 정렬됩니다. Publish 버튼을 누르면 공개됩니다. / Published posts appear immediately, sorted by this date.',validation:R=>R.required()}),
 defineField({name:'category',title:'기록 종류 / Category',type:'string',group:'settings',options:{list:[{title:'일기 / Diary',value:'diary'},{title:'독서 모임 / Club notes',value:'club'},{title:'독서 실험 / Experiments',value:'experiment'},{title:'배운 점 / Reflections',value:'reflection'}]},validation:R=>R.required()}),
 defineField({name:'author',title:'작성자 / Author',type:'string',group:'settings',validation:R=>R.required()})],orderings:[{title:'최신 기록 / Newest first',name:'newest',by:[{field:'publishedAt',direction:'desc'}]}],preview:{select:{title:'title',subtitle:'publishedAt',media:'cover'},prepare:({title,subtitle,media})=>({title,subtitle:subtitle?new Date(subtitle).toLocaleDateString('ko-KR'):'날짜 없음 / No date',media})}});
export default defineConfig({name:'lumi-journal',title:'SECRET BOOK CLUB · 글쓰기',projectId:'b8hapo09',dataset:'production',basePath:'/studio',plugins:[structureTool({structure:S=>S.list().title('루미의 노트북').items([S.documentTypeListItem('journal').title('저널 / Journal')])})],schema:{types:[post]},document:{productionUrl:async(prev,{document})=>`https://lumi-secret-book-club.vercel.app/journal/${document._id.replace(/^drafts\./,'')}`}});
